import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";

import { create } from "tar";

/**
 * Maps a compression name to the corresponding archive filename suffix.
 *
 * Mirrors `compressionToSuffix` in `src/archive.ts`; intentionally duplicated
 * here to keep `e2e/` free of `src/` imports.
 *
 * @param name - The compression name (e.g. `"gz"`, `"none"`).
 * @returns The archive suffix: `.tar` for `"none"`, otherwise `.tar.<name>`.
 */
function compressionToSuffix(name: string): string {
  return name === "none" ? ".tar" : `.tar.${name}`;
}

/**
 * Builds a tar archive in memory by writing the requested file tree into a
 * fresh temporary directory, archiving it with `node-tar`, reading the
 * resulting bytes, and removing the temporary directory before returning.
 *
 * @param files - Map of archive-relative paths to their contents. Missing
 * intermediate directories are created automatically; forward-slash paths
 * are recommended.
 * @param opts - Archive options.
 * @param opts.compression - Compression name. Only `"gz"` enables gzip
 * (matches `src/archive.ts`).
 * @returns A `Buffer` containing the full archive bytes. The temporary
 * working directory is removed even if an error occurs, so callers do not
 * need to clean up after the call.
 */
export async function makeTarFromTree(
  files: Record<string, string | Buffer>,
  opts: { compression: string },
): Promise<Buffer> {
  const tmp = await mkdtemp(join(tmpdir(), "e2e-tar-"));
  try {
    const tree = join(tmp, "tree");
    await mkdir(tree, { recursive: true });
    for (const [rel, content] of Object.entries(files)) {
      const full = join(tree, rel);
      await mkdir(dirname(full), { recursive: true });
      await writeFile(full, content);
    }
    const out = join(tmp, `out${compressionToSuffix(opts.compression)}`);
    await create({ file: out, cwd: tree, gzip: opts.compression === "gz" }, ["."]);
    return await readFile(out);
  } finally {
    await rm(tmp, { recursive: true, force: true });
  }
}

/**
 * Description of a single entry inside an intentionally unsafe tar archive
 * generated by {@link makeUnsafeTar}. The interpretation of optional fields
 * depends on `type`: file entries use `content`, while link entries use
 * `linkTarget`.
 */
export interface UnsafeEntry {
  /**
   * Archive-relative entry name written verbatim into the tar header,
   * including any unsafe forms (parent traversal, absolute paths) used to
   * exercise extraction safety checks.
   */
  name: string;
  /** Entry kind. Defaults to `"file"`. */
  type?: "file" | "symlink" | "hardlink";
  /** Link target. Required for `"symlink"` and `"hardlink"`; ignored for files. */
  linkTarget?: string;
  /** File contents. Ignored for link entries. Defaults to the empty string. */
  content?: string;
  /** Owner UID written into the tar header. Defaults to `0`. */
  uid?: number;
  /** Owner GID written into the tar header. Defaults to `0`. */
  gid?: number;
}

/**
 * Builds a single 512-byte POSIX `ustar` tar header from the supplied entry
 * fields and computes its standard checksum.
 *
 * Used by {@link makeUnsafeTar} to assemble intentionally unsafe archives
 * (parent traversal, absolute paths, symlink/hardlink type flags) without
 * depending on `tar(1)` flag combinations whose behaviour can vary across
 * implementations.
 *
 * @param fields - Entry fields used to populate the header.
 * @param fields.name - Entry name; truncated to 100 bytes by the ustar
 * format.
 * @param fields.typeflag - Single-character POSIX type flag (`"0"` regular
 * file, `"1"` hardlink, `"2"` symlink, etc.).
 * @param fields.linkname - Link target; truncated to 100 bytes. Required
 * for link types, otherwise pass `""`. Defaults to `""`.
 * @param fields.size - Payload size in bytes. Should be `0` for link
 * entries. Defaults to `0`.
 * @param fields.mode - File mode in octal. Defaults to `0o644`.
 * @param fields.uid - Owner UID. Defaults to `0`.
 * @param fields.gid - Owner GID. Defaults to `0`.
 * @returns The 512-byte header buffer with the standard tar checksum filled
 * in.
 */
function tarHeader({
  name,
  typeflag,
  linkname = "",
  size = 0,
  mode = 0o644,
  uid = 0,
  gid = 0,
}: {
  name: string;
  typeflag: string;
  linkname?: string;
  size?: number;
  mode?: number;
  uid?: number;
  gid?: number;
}): Buffer {
  const h = Buffer.alloc(512);
  Buffer.from(name, "utf8").subarray(0, 100).copy(h, 0);
  h.write(mode.toString(8).padStart(7, "0") + "\0", 100, "ascii");
  h.write(uid.toString(8).padStart(7, "0") + "\0", 108, "ascii");
  h.write(gid.toString(8).padStart(7, "0") + "\0", 116, "ascii");
  h.write(size.toString(8).padStart(11, "0") + "\0", 124, "ascii");
  h.write("00000000000\0", 136, "ascii");
  for (let i = 148; i < 156; i++) h[i] = 0x20;
  h.write(typeflag, 156, "ascii");
  Buffer.from(linkname, "utf8").subarray(0, 100).copy(h, 157);
  h.write("ustar\0", 257, "ascii");
  h.write("00", 263, "ascii");
  let chksum = 0;
  for (let i = 0; i < 512; i++) chksum += h[i] ?? 0;
  h.write(chksum.toString(8).padStart(6, "0") + "\0 ", 148, "ascii");
  return h;
}

/**
 * Pads `content` with zero bytes up to the next 512-byte tar block boundary.
 * Returns an empty buffer when `content` is empty, since zero-length entries
 * have no payload blocks following the header.
 *
 * @param content - Raw entry payload bytes.
 * @returns A buffer whose length is a multiple of 512 and whose first
 * `content.length` bytes are `content`; trailing bytes are zeros.
 */
function paddedDataBlocks(content: Buffer): Buffer {
  if (content.length === 0) return Buffer.alloc(0);
  const padded = Math.ceil(content.length / 512) * 512;
  const out = Buffer.alloc(padded);
  content.copy(out);
  return out;
}

/**
 * Hand-rolls an uncompressed tar archive containing the supplied
 * {@link UnsafeEntry} entries, terminated by the standard two-block
 * end-of-archive marker.
 *
 * Intentionally bypasses `node-tar` so tests can construct archives that a
 * conforming tool would refuse to write — parent traversal, absolute paths,
 * and symlink/hardlink entries pointing outside the archive — to exercise
 * the extractor's safety checks. The resulting bytes are always
 * uncompressed (suffix `.tar`).
 *
 * @param entries - Entries to encode, in archive order.
 * @returns A `Buffer` of the full archive bytes ready to be written to disk
 * or served as an HTTP response.
 */
export async function makeUnsafeTar(entries: UnsafeEntry[]): Promise<Buffer> {
  const parts: Buffer[] = [];
  for (const entry of entries) {
    const type = entry.type ?? "file";
    if (type === "file") {
      const data = Buffer.from(entry.content ?? "", "utf8");
      parts.push(
        tarHeader({
          name: entry.name,
          typeflag: "0",
          size: data.length,
          uid: entry.uid,
          gid: entry.gid,
        }),
      );
      parts.push(paddedDataBlocks(data));
    } else if (type === "symlink") {
      parts.push(
        tarHeader({
          name: entry.name,
          typeflag: "2",
          linkname: entry.linkTarget ?? "",
          uid: entry.uid,
          gid: entry.gid,
        }),
      );
    } else {
      parts.push(
        tarHeader({
          name: entry.name,
          typeflag: "1",
          linkname: entry.linkTarget ?? "",
          uid: entry.uid,
          gid: entry.gid,
        }),
      );
    }
  }
  parts.push(Buffer.alloc(1024));
  return Buffer.concat(parts);
}
